import {URL_NGROK} from './In4User';
const IN4_APP = {
  getDataApp_Home: `${URL_NGROK.url}/getDataApp_Home`,
  getConfig: `${URL_NGROK.url}/getConfig`,
  getQuestion: `${URL_NGROK.url}/getQuestion`,
  getLession: `${URL_NGROK.url}/getLession`,
  getPart: `${URL_NGROK.url}/getPart`,
  // getPartListening: `${URL_NGROK.url}/getPartListening`,
  getQuestionPart: `${URL_NGROK.url}/getQuestionPart`,
  getWord: `${URL_NGROK.url}/getWord`,
  RankOfUser: `${URL_NGROK.url}/RankOfUser`,
  UpdateAvatar: `${URL_NGROK.url}/UpdateAvatar`,
  UpdateName: `${URL_NGROK.url}/UpdateName`,
  UpdateEmail: `${URL_NGROK.url}/UpdateEmail`,
  UpdateScore: `${URL_NGROK.url}/UpdateScore`,
  UpdateHint: `${URL_NGROK.url}/UpdateHint`,
  getUser: `${URL_NGROK.url}/getUser`,
  UpdateOverviewSetting: `${URL_NGROK.url}/UpdateOverviewSetting`,
  UpdateTokenNotification: `${URL_NGROK.url}/UpdateTokenNotification`,
  initConfig: `${URL_NGROK.url}/initConfig`,
  getAllWords: `${URL_NGROK.url}/getAllWords`,
  UpdatePassWord: `${URL_NGROK.url}/UpdatePassWord`,
  getTotalFriend: `${URL_NGROK.url}/getTotalFriend`,
  getScoreFriend: `${URL_NGROK.url}/getScoreFriend`,
  getTopRank: `${URL_NGROK.url}/getTopRank`,
  searchFriend: `${URL_NGROK.url}/searchFriend`,
  getEmail: `${URL_NGROK.url}/getEmail`,
  getUsername: `${URL_NGROK.url}/getUsername`,
  getThanhTich: `${URL_NGROK.url}/getThanhTich`,
  writeLog: `${URL_NGROK.url}/writeLog`,
  showLogs: `${URL_NGROK.url}/showLogs`,
};
export {IN4_APP};
